//
//  NuptialWidget.swift
//  NuptialWidget
//
//  iOS home-screen widget for the Ant Nuptial Flight Predictor - the
//  counterpart of the Android AppWidgetProvider, and kept deliberately in
//  step with it: the same five Ant Flight Index bands, the same palette
//  (res/values/colors.xml + values-night), the same calibrated odds line and
//  the same ant glyph, which is a wingless worker on quiet days and a winged
//  queen once a flight is likely. Change one side, change the other.
//
//  Sizes. Android lets you resize one widget between a 1-cell glyph+word and
//  a wider cell with the odds as well. iOS cannot do that: a placed widget
//  has a fixed family, and there is no 1x1 home-screen family at all -
//  .systemSmall already occupies a 2x2 block of icons and is the floor Apple
//  offers. So the nearest equivalent is to publish several families and let
//  you pick when adding: .systemSmall mirrors the compact Android layout,
//  .systemMedium mirrors the wider one, and the Lock Screen accessories
//  (iOS 16+) are the genuinely small option.
//
//  Generated by scripts/icon/gen_ios_widget.py - the two glyphs are the same
//  Myrmecia artwork as the app icon, embedded as base64 because this file is
//  the extension's only target member.
//

import WidgetKit
import SwiftUI

private let appGroupId = "group.au.com.bitbot.nuptialflight"

// MARK: - Bands

private struct Band {
    let bgLight: UInt32
    let bgDark: UInt32
    let fgLight: UInt32
    let fgDark: UInt32
    let fallbackLabel: String
    /// Winged queen once a flight is plausible; wingless worker below.
    let winged: Bool
}

private let bands: [String: Band] = [
    "noFly": Band(bgLight: 0xECEDEA, bgDark: 0x262B27,
                  fgLight: 0x55615A, fgDark: 0x9AA69C,
                  fallbackLabel: "No-fly", winged: false),
    "quiet": Band(bgLight: 0xF6E2DF, bgDark: 0x3A2523,
                  fgLight: 0xA04A42, fgDark: 0xE09A92,
                  fallbackLabel: "Quiet", winged: false),
    "watchful": Band(bgLight: 0xF3E5C8, bgDark: 0x3A3120,
                     fgLight: 0x8A5B10, fgDark: 0xDCB573,
                     fallbackLabel: "Watchful", winged: false),
    "promising": Band(bgLight: 0xE9F0D8, bgDark: 0x2C331F,
                      fgLight: 0x5E7D2E, fgDark: 0xAFC97A,
                      fallbackLabel: "Promising", winged: true),
    "prime": Band(bgLight: 0xD7E8DC, bgDark: 0x22352A,
                  fgLight: 0x2E7D43, fgDark: 0x7FCE96,
                  fallbackLabel: "Prime", winged: true),
]

private let neutralBg: (UInt32, UInt32) = (0xE8EAED, 0x2A2C2F)
private let textPrimary: (UInt32, UInt32) = (0x1A1C1E, 0xF1F3F4)
private let textSecondary: (UInt32, UInt32) = (0x44474A, 0xC7CACD)

private func dynamic(_ light: UInt32, _ dark: UInt32) -> Color {
    Color(UIColor { trait in
        let v = trait.userInterfaceStyle == .dark ? dark : light
        return UIColor(red: CGFloat((v >> 16) & 0xFF) / 255.0,
                       green: CGFloat((v >> 8) & 0xFF) / 255.0,
                       blue: CGFloat(v & 0xFF) / 255.0,
                       alpha: 1.0)
    })
}

// MARK: - Timeline

struct FlightEntry: TimelineEntry {
    let date: Date
    let bandKey: String
    let label: String
    let odds: String
}

struct FlightProvider: TimelineProvider {
    func placeholder(in context: Context) -> FlightEntry {
        FlightEntry(date: Date(), bandKey: "prime", label: "Prime", odds: "1 in 7")
    }

    func getSnapshot(in context: Context, completion: @escaping (FlightEntry) -> Void) {
        completion(loadEntry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<FlightEntry>) -> Void) {
        // The Flutter app reloads this timeline whenever it saves a new
        // outlook, so the hourly refresh is only a fallback for stale data.
        let next = Calendar.current.date(byAdding: .hour, value: 1, to: Date())
            ?? Date().addingTimeInterval(3600)
        completion(Timeline(entries: [loadEntry()], policy: .after(next)))
    }

    private func loadEntry() -> FlightEntry {
        let store = UserDefaults(suiteName: appGroupId)
        let percentage = store?.integer(forKey: "_percentage") ?? 0
        var key = store?.string(forKey: "_band") ?? ""

        // Band key written by 2.20+; fall back to the old percentage
        // thresholds right after an upgrade so the widget is never blank.
        // Mirrors the same fallback in AppWidgetProvider.kt.
        if key.isEmpty {
            if percentage <= 0 {
                key = ""
            } else if percentage < 50 {
                key = "quiet"
            } else if percentage < 60 {
                key = "watchful"
            } else {
                key = "prime"
            }
        }

        return FlightEntry(date: Date(),
                           bandKey: key,
                           label: store?.string(forKey: "_band_label") ?? "",
                           odds: store?.string(forKey: "_odds") ?? "")
    }
}

// MARK: - Ant glyphs

private let workerGlyphBase64 = [
    "iVBORw0KGgoAAAANSUhEUgAAAHgAAAA8CAYAAACtrX6oAAAPVklEQVR42u2de5RdVX3HP797Z/IOCYYQCAsSJIHIKwhBwIYCxeiy",
    "ldp2aUVYVau0Yl11VcW2q1mttVqRVkuXVIRl5VFruwxYBe0SSwGNEFOIQEOQQMgDyIuEvEMgM3Pvt3+c77abw70zd2YyD8bZa511",
    "zpy7zzl779/+vR8TjLZBa5IqQCUiuvz3VOAU4BzgjcBsYCIwHqgB8qMHgb3APmANcC+wPCJ29vTNGF32QQNuNSJqvr4Y+F3gLMNg",
    "DfAIsAFYD+wA9gAdQAWoAhOAmd4Ib/BGuD8ibpEUABGh0ZUeGuC2+3yypKWStkq6WdLFkmb08Z2nSrpIUnV0hYcWuG0+v1/SLkk3",
    "SjqqjN2S2iW1+brS5Ej9KqMrO0zIss9XSKpJurQE1Goir33h56OAHmLgSgpJ50k6IOk9vj9mFDAji+9+Q9K9CbiDPY7RnTQwwA2g",
    "y5g6C7jX17VRAI+AZnWlGhF14Fngbb4eVUtHoPR8oYp2WS54jbaRY7lC0vWS9kmakwN/tI0AXmxpeqykhyStkjRtVMUZmVg8R9Ie",
    "SbcZ8KNYPAL58SLz40+N8uORC+QvSeqStCCR8NHVaY3PVYYric5syGMkTZG0TdK92W/xWl34dJSN5r/4rZ+LVm1m/+3lGHv9TCub",
    "rpvfk+p0RWa+HBAgx6F2ZvudApT8nz0Y48NHHaj35NPM/ar++3AKH+lOYGVE1E0Oa731jzbyq5bmVU9zA5KQ9Ipxl/y+VeBEj+8E",
    "YBqFn3cr8FHgWGB+RGxwX9kgMqzIT1uz3SppkqQZko6TNNeS5HG+N7VMVpN02YzcJgBIOlbSQklXSlpnntYh6UeSFiWe1wwrMsy9",
    "QdJPJb0zowqVzG3XkEKUJeDcxee/x0v6oKSf2NHQqB30eamk88tS95BhsBetUsZOScdQhJ+8wbv1SB/TgEk+APZnxxZgLfAE8CSw",
    "IiI6G30nYYakC4GvAvPyz2fzeRn4s4j4shdLZYw0lp8B3GnMHxcR85rMdyZwAXCMv/k6f2cL8DDwcEQ8nPU/Cfgy8NbsNfVsjGmc",
    "Fd9PAP0m8OmIWFumUoPJU9tK2DtP0icl/aektd3s1lbaTkkrJH1W0qm59JlhyExJq92/y0fd53Sv5uvP5W67BtLsx62TLpC0Q9Ld",
    "kpYb666X9A5Jf+l5dde2SbpP0gWSZkta7/sd2Vi6a7Vs/E9KOnPQVaicbJi8XirpLkkvlgZbl9TpyXX6SIueHwk4qW9X6T0HJP2r",
    "pPkloFzl31/MNtPBbKHSGDp8/ddlN132ri84wmJ1NwuvbOOU55WuU9staYOvO3u5ueuSXvb1KkmzknA6aFgraaKkP5W0sjS4rgyI",
    "9T5ibz3DxBzYeyV9zqa+iqR7fP8hxzVJ0jWSPp8BpVbC6j8qOeATn/x+k3nk88mpRHdj72qyMXrb0mb9xoDryKXFuMDCiLId2tUP",
    "gLbSOrP33y7pXAO1Q9K3MsEqYfnfZIDKN0yHpN9xn3E+v9cY09lPgDTapIfiPQclnZixqPbuhM9+xftI+pOMfHQ2IKcD2WoZudvs",
    "6w2SbvK9tXkAm6S/yBa6ngHveUlnuc908/q+kNLBmrNMLV/XyCLWG+NINNFNRRGL+0XgY/6pK9P9Brvl0ua3PZb3WKd8AlgFfD0i",
    "lktaDCwGxvqZNO4ngDcBpwEP+J3D1Uwoz201sA5YaYn9wYjY08Co09R+EGXMtQrRDtwKvNcLVB0G0QgJUHcDc4DjS7/vAi4FHgP+",
    "F5juhYrs2euAn1vNGsoN25f2EvAMsAz4D+BHEfFiplIm4069IYCT3gm0Azd7sTr94HC2ldYMrLHAo8AdwF9lwI0SFdhMkSGgAZxX",
    "vfTt3mCuKNJUlgGvB+Z6jmHYpH4bgG8B3wEeyewHbcboehnAVQ/si8AnhjlwGwFHHv/LFGke0eJzAwnUWmbmbGWjYmr5kYi4QdKR",
    "wJXAZ7J+nX5nem8H8APgduCOiNiXI22UrEQfAP7Zg20boUFiAwHkrpJt+mlTiUklwKsBtqZ76flrgU85aK/D8Pk1s6SLgMtLwG7P",
    "/n4OWAJcHxHrJFUi47uzgf+xeVEjELjKFrtyCLG2CxhjknqvBbwvAPcAVwPz/XtPm2wtcE1EfC2ZWFOfnK9K+ihFNuJO4LeBqf5u",
    "pzfUWYbhd4G/TRg8ySj+tteg8FG2Rz8FHAVMLnmqKk34XW94ZY51OeldCvy+760BfhARv262907gBuAIS8ZVA/wlY9xqA+i7EbG1",
    "iUer6ntl+/9cYGZE/Di7N4cic3En8L1wKuNU4B3AB17DAO7wwl0FHGZBq27e1k6RY7vYrrvLS1hYKwmdkamKkeXqltdlDfAV4OaI",
    "2Ctpip0mL9pBsSkiJGkJ8G7gH8wCx1pW2B0RW5u5QntwsZLlGb/qXv7AOEnjff2dYWwAaGQQqGX272T4P8mGmlsdqipJmyRd7jku",
    "yGzHT/Zyrnv8zBLb4w9rkGj2PRuDTsmiTT7s57/djcu112yjG9flmOQubYuIl1OUBfBhO6hPbsDAh5uAlC9Im8f7iYh4UlJExPsl",
    "3QocR5ENv9pzTNahJcbo84AzrZJMBaaYEuyxe3AW8N/Av1k1WRkROxpoH6ktNzWcExGPAzVJ93l8b5Z0vPXZlMqiV2Fd6xkUtSb3",
    "at2lOp4i6ZnM5TVcWr1kp15hZ/8OuysXZRjxKkN98ihJ+lAyBTZKGJN0mKQjTNmWuO/7GmBJ2Q2Z1u+SUuRkwtBHff/iwXQHtuWQ",
    "l9QWEY9Lepd3+OxhhMkB7AbGGWOuMrZMAbaZ11WSxOkN0ZYJWWlXp4z6jSaL7SnsxvLHviTkSDrOfXfaulcBOnvgk+v8rRRAUI2I",
    "TklLgdMt5d7DUCSfRUSXgfwQ8BbgJ9kC1BgaK1Uif7uBT1NEUnQCz0fEyxHxfCag1PMEsIjoiogyQI71+Rn377IVqJ5tpHCs15EW",
    "mJ5zn65uYqbS/R0UCWenl6T7+/3uBaX+g5tdaCBXI2Kteck/ZoVAOgdpYLXMBp50wq0UBUqmGNhbM8CqhRCXtNAzLcFuz+/7HSou",
    "ow4cbX69w+ZNSoaKZoERL1j1OUXSYRl/XQUcAN4kabwpRAxJ+qjJdTUi9kbExy3i/9zYnDw0tZ4m3AcBKgkI1cwD9AcGrEyep3oR",
    "d3tB6y0KJHUv6ExTgX09eNiO8mZ6AdjhZ9VDymgqkfQ0RSmk4zPAb7IjZJadJYNS5ajSnYSWIg0j4nbgQuDzHmhbpiPmgKmXQkub",
    "HfXsmVwHrfr4qXns+XZ8TDZAkhVqU1rQPsz3aBsY9jQBWlr06SVSXmkhDDc9+7jPiQ+32833kP8+e7Dysys97foMm7dHxGLgV4Er",
    "7LJ6IfOrVktG8Nz+WrYaVbJnkpqxGfgX4DeB34iIL1kdOdkmuOcoakORkcyWakNlpHCyMXNLRBzoYf4JwBt6gW1pLE+byp1WWucV",
    "Pp/XCsk/pFJ0T/pWVqVtHbBO0k02v50KnOvJzDUJnWhrzVjrlEmSPWj+t9d65lMm/csowk93ZUAZ7/5T/J4NFnoANvZBAhdFCG81",
    "8W/zWzUB0tElAPfGXLra8zu1JFA96vmfnYLzrbNrSAGcGbzrBnTY57gduM9HwpTpPiYaYyZmfHu/J77Fqk29gZCSNkOX+eYMP78+",
    "c/Jv7GP8dwLas00CHvK/Z5QArBYRIUxhNgPzDMhOz+0JA/9EYF5ErLI+XBtyAJcAXQ4SSBhSj4htwLZW84tKz+bvzhdaJtG/4nvr",
    "+6hqHOPztm6AVvO4ppU2U6tYVrUm8jPgEuDYiFgvaUxEdFgfPsNeplWZRWv4FWFJ6on1zVo5McwWnPJRzTIOfvFsN6TyeG+CbRQZ",
    "E7Veks0cU4/xptjZgzQ8wVSoy9SmL/xymSnYSaUx/JfPZw4GH64c6uoySTDLgFc+au6jnpFcFduI91uHnGvs3VqmJi22GeaBL/Sw",
    "ESa578Zu+vYUmbHU8kfZ4PGANYKzJU1IfPiXqoySTY41GxpO92JVgcOBn5nU9WXsU7xZtvVA4se672bXu2pZEMr6rbHZ8nzz4S7P",
    "azfwQ6tKs5Nx5ZetTlaa8FwbBW4zqRZF1ElfjQTTTAl6khHajcXb+gKAzGz6dYoktNf77+SgWGKjzZsHGg7DvdLL2ykc+cspok0C",
    "eLAf75sGdETEgSwsptkGa7PE35/oktus6r0r3feGud+8/cqhqoA31JUB2uy03iTph5Im2Jn/lKTpDVSaVqu+LpO0opm7LsvmmGtX",
    "6Vf66tpLDndJt0ja7vyqanb/GrsPFw6k+7AyDEsOjbE99322G99olWI6cFdEbLfHS73J2nebaB7cCokPCk9Sf9t1lh0+abkiuV5v",
    "srC1OA+5GUlYGiWVKk9RXSRpf1al9Q47+S/obaW4Uobkw46uaFj5tYTBnZL+vj/YlVGOzxhbL+KVlWiv9f1Lhqoa7aFMZmvvqQi2",
    "S97/u6SXXIVmqqRzHON0d7OyCr0oYXSLE7TTwo/NxlXJyOcsR4p8rb9V6bJ33+h02I9lpSgmOiplXcZ62l+zlXdKWDXVC3mu61nc",
    "4aC2lQ7AxyWHHnA65YJ+8MMUxnOSefk384C5Bv2nSHpE0gOHom5GBtA/9gZb5aC9qQ6Res45wWOGbZWdbvTZuutWXEbhnDjcxzQb",
    "AsZSOB8eA+6MiDv97Nv5/8DxP0wB4X2tQpN0WUlvpPBajQW+7+9usFS7A9gbEQcl/RPwEWBWRGzsa+Wecr0RSUdTBDdeZmn7x9aJ",
    "z6DIq7rW49hglS5aqT401AA+gSJOuNODfpEiKmMXsDFlyfmZhcBngYU2Fvx5RNyZohf743nJxjOFIlrlLd5o7VbH6jYl3kBRTGap",
    "deaLI2JLzj8bpJ6oNyWgJB3hzTvfOvFE4Pco3JnPA4siYnWplFOu2imz4Wu4kukjJZ0m6bck/Z3VoJckPebox/ZDXVqoQRxxOIJy",
    "kknzhEzYWijpWUlbJL3bcVqtSOs9yiNNfjtc0tVmI2v9zzzm9Gf+A43BiSxO8u481Rgz2eR6qnfvQYrcnJUmWXdl0ZGHvKRQ5gVr",
    "mjydYft0x09/0Jj1IIUXaL3J+mbbq/f2ZpylMbwiztnlGz5kKjPZJs9n/M3dNsDspIgrWxkR+5uZUwcLwBMp8mXGmd/uympl7QF2",
    "2Eb7Cr/woNeK6p6knkARzXKOTagTzMfrliWus5zQ5w1poFezlJTDKHzH8x3CfARFWs4Ys5WdwNURsaaZfPJ/KaX6cXm9rRQAAAAA",
    "SUVORK5CYII=",
].joined()

private let queenGlyphBase64 = [
    "iVBORw0KGgoAAAANSUhEUgAAAHgAAAA6CAYAAAB79J21AAAPd0lEQVR42u2de5CdZX3HP7+zZ7O5EBISCAkXIxAjRAgBVASUags1",
    "RmtbRVLLTLl0lLHWTqe1Y6elU6vTYZTBcdqOrcx4q9qxNVgHLe1Y0FgQlFsSuQRiSDb3hEvu191zzrd/vN83Pryes+eyu2c3Ie/M",
    "O3vO+77ned/3+f7ul2eDE1tXN0k9EVFNvr8BWAhcAcwDZgB9QA9QAUrAEeAgsA94AVgOPBwRzze7X5yY8q4BW4qImj/PAW4ErgGm",
    "AzuAR4F+4HlgG7DHoGKQJwIzgTd4P9PXfhHYCxAROjHTYwRu8vmvJK2R9KCkmyTN63DM2ZIul3SSv59g1jECN7xPl3SfpNWSri0S",
    "gKReSWVJPf5eSn4bybGypPKJmR0/4JYkTZH0M0n3S5qanMvBjE7HHmkqPCEG2pu3sv9+wWK57HnsGgeWDVq6A8h7+O8rwC4YZ+lv",
    "SH//alb6Nqoqkk4D3gX8pb/3RsRg1wA2CBpNMVUgoPR+xzMR5IQ/w383WqRWu/kQZUmXAecBpwOnAif7oWYCk+2TTUh+cxAYBA4A",
    "u5N9D/Cy/bRt3g8CAxFxpJFP6JdWwvW14wTgmqQeuzJ7gRsj4mFJE4CBrlGZpOuBdwOLgItG0DfeBWwHNgObgA328/qBl4DtEbGz",
    "gUsRx4Ooz4MakpYC/wYsjoj/lVSOiEo3xQj2py4Dfh24Fnizoyn5RA/W0dX1tlKT87JjvxnYCPzC4K8BnouIzY0mKxHxtWMF9DzA",
    "IenrDmy8KSI2p4GP0ebgniwI8kuKknQyMB9YDLwXWABMSQCqerJ7mgCpgs7NCaCeeX/QoqwfeAJ4DFhlItgfEYfrAF5KAK+NV1fJ",
    "H08CfuzPVwGHuxF9isKD9FgkVgsi880G+h0W5RMTEGstcvZQwA9FLFuBZ4CfG/jVwPqI2HWsiHYTYw14PfBT4B6HKkvpXI8qwENY",
    "vkfFoaQpFuNXA+8ErixwY8W/KdG+LleBABqJ+502XJ43h68CVkTE9iZifUxBz/WupMXAfwM3R8RXR9ttijYosCjGpwDnA78LLAFe",
    "ZzE0EmAXga8loBeDBEds0K0GHgIeBp4CdkbEvgZivdZtPW6m6Y2IAUlfAn4PuMC2CKOlYqKDhyzVAbsEvAV4j7l7UaKzSQAqjYCV",
    "XitweU+dMfcDT1uPP2bw10bEy90U68n4r3D/JM2yuvlJRCwtphDHDOAWxfhksvzmlcBvAm+zPz2qDGLgSaRGuu0F1nlfQZaaWxkR",
    "OxqA0pMQUTpuvbGrRcLIY8QFUKeRpfj6/By/D3wBuC4i7pbUC1RHmpNjhOOuZT/kYHJ8sq3G99pNOA/o7RLgQ4n1PcCz5qRngMc9",
    "8XsKYEUzYyhVYZIiIfYFwPtM6OdahaUJ/LMcI/idiFhZzBuPOcCJyC6KoAkGcjZwmiNks2yNX+VombpYcJAC3sguqAErgSetw58G",
    "1lu0VyxWz/I+w2NsAX4REesKhtQpwG3AR4BJTZ4rLGG+AdwREf0jKbJjGLqlVNDDc6x/rwYuBs4G5nSBW4cDejOLfbNB3gfMTcK5",
    "qXje6CDNd8mqK04F7rZqymMGjWyPKBD688CtEXH/SEW7Yjg1RZJm+kU+aB95ZkFH5S+oQpAjxingqQHX0yAgU+998u0HHmOx4829",
    "bcQGBsli/ruA90TEQyMhrqPdshOH3eYANwPXm1upE+VqJ/gx3jlcDd6peL6UEEFPB/es2F5YA1xu0T0syz464NobgL9xVIYk/dVt",
    "ztQ4JJ5aMhedbjlxfDwi7pQ00cB3FIMvtZERmSrpn4GvG9zB5GF6xmCyo8kkqQVfeqS30jDBTaXCEkmTIuJwRFQiohoRSuq2Ytgc",
    "nIB7DvBVG1DVJMAwluLzRWCa/crjcdsPPGjD6+e27FdExKGCe8ZQnB0txE4XAd8mK8qu1PEpGQOxfIAsM3MFcEohaXGIrDD8Irs0",
    "RVE+aL/3PPul41HU19Phe2zR/4QsWfHjvJDC3FyuFyiJJpx7AfB9O+mD48jlkYmtt87ElIA/AX7LAYbiZFUc4JgLTB1FgGsdiuv8",
    "eVb49/MtpWoJc1UN9n8A/wmsyoNLDjgdTZ/GEEXaM4EfkVXRD45jf7bedsjvNnEMjKxSHaOrFW8iJdqVwFt9/FrgX+yD5wSaRucG",
    "yLJTdwP3RMSehhyc54Qtmr8L/PYwTP7xwOUxBBAj6cLl7mE5CYX2J55GCnytgcFX9vOsBt4fEauTapALrY7OBT6e3KdIUJvN0f8I",
    "rAUiGpSXfBT4p2OQc4vg1gO52iBpMBx9mQO0jKzo8CNk6cDpwJ+SpVWbEdNu69bbImKTDSjViRi+E1hKVuD4G7aN7rNRdjJZJm+u",
    "Veuni+0TPe532SWpIqmqY3M7KOkxfx6UVPO71ArX1ZL3rLUwbj5OxXu6fcMdDEv8/dN5FknSJ3zsiKQtkl6S9KKkZyXdK+lTkq6o",
    "18tUwKZ4/BRJby8cO13SH7vvac7RmiFJMyW9S9IHJS33A1WOMWBzADZLulTS2jrv8Q+SPizpQOG3FUkDyT7ovzmR1yOCAUk/lPT+",
    "ZB4X+vh/5W6MpD4DW5G0WNI8SfMlneFARlpG3NR1LfYntdSz5Iv6/Pk1kvqTFxvPgFYSrjpS4J6rzMn7JW2X9JnkfVcaiIckbWjx",
    "fkckbXRn4B2Srsy5KgdH0gxJTxrQCQn3/avHuKVOW1Bv4tO2lfTJ22EaNLJFDOEivdU6YbqVec84Cwk20qHLgFuAg36PKWRpyp0R",
    "sSqpqFhhY2iB/eXLyMqOZtk/nuSc7ULgjTZevgj0R8RzDYrq8irPb1oHz8ubtCXdBHzF5260Tq6OSV9v0jT1AeuzXJeNt22HpLsk",
    "PSzp+5JuzkVeve4756mRdKG5+oFm5a6S7vS9bqzDOcXxe5MeYLnALj+3yHO4zkUQXenprSuz7SaVI+LbkqrAXfaLxzKSpSQStdac",
    "tz4iPlwPnLznKi0HTlyU08jKiNb7/ITEuj6aI/a53NXZasIvAYNNcrVr/HcB8D8mhA0OOV5qSbGqXnPfaATHGQLknoj4DllryyqD",
    "W+tyA1WtkIJcBXzW5zakPba5HkxFXkQoD9Ynrsqp/rze11Z9TQ5czdeLrHBhENjic5UhRGotSdwfAC709wmu437UY142Almn4WeT",
    "rMPKEfEz+1xfTpLhlVEGuuooTV4Et9UTuCmJUPXnwBnIaov6LO/4W1un9TXdphngHfYzW5Uya8kS9wsLxx81YV3eLe5oSkGJuH45",
    "Iv4QuIGsbqnsic85rDpMcaPCWD0Wnf3A3wLXmZNetEOPa6I62fKw37omWbbTnczYhBc6afKOstTb57HPlDTDz41DkAPAG22YVUdb",
    "D7ckIgxyyZGufydrUPsEWUViqU5OOAeqkuzVZC8eTysi8rEecVju2oj4lK/tI6uBOsX32d6hHp/tv5sahA+jcN0WYG+zJRMsPSIB",
    "cypwrqODZaf81jr6NM/Xl7puZDV4+FriRr0EfFbSXQ7DLSarg17gyW+3DjovI10DPADcCzyRB849OWcmk31N0rfUTgWoEh2832HF",
    "oTj46D1zkFoohMvv8QTwMeAcsuL7ckQclvSI5+ki4LnRTlW2bRFbL+dVlbvJmql+6kmc4Yc/H3gNWVXl9MSvzNtGjjj2usn7GmB1",
    "RPTXcddKbvfIxerLHrvqz+02ZU+0Fb0x71gcQm+f4b/r2yhxSgEOW8x5J2eQ5apvsjW9bNwBnHBzrdDdIDd0P+idRn1BLRSR520k",
    "lSTC81oTxx5zxY5koTC1+Nxy4GO2dXuzQvMzCqpArUo6sr7nvSZ47FpJ0nIT55skTQIOFy3/ruvgoSYsImq2XmuJq1J2uKzX33uS",
    "fKfSeGq6NlQuITymCpN6ntNhFU/8BluqrQKcc8oUG08bWuDK2UnDelsNAZYOjwDnSzop73qwDfE4cAkwu6C3xxfADQBPfcpBc2ut",
    "0B5a8zWVpKCs1kTkLSArtcnXcdwQEXs7iOFOstrY2oKYPctcuLUdSZHM63KyDsJZhUVvvufA0bmjvaTkqDvaCfCv2NtY/kBuBZlP",
    "1k5ymk8/mb9Di+PlkzjRn7cOUfSQL6Ayi6yrYXubAOfbAzY4LygsP/VD/317h+OOL4CHucREkPUz9dqYy4MHT3U4OVMLFrh+lR5D",
    "FuUTzcH7ktWAWjXmwkS4BrjBY+bHn7U0us7ivPaqBdgTs5Sss/9HrlHa55BlJwDnEmBbk+sm2Ajd3a4B5Ot7HJ5cBlzvDFbVTeA7",
    "yTJ15wNX5LbLqwrgnGPc/3QN8H/Wn4sc8tuYpOna2SYmi74MRSB50uFQm6qgqMe/Yp/71kJg41se+2OjGfAojeOVafpsoH3A1uzt",
    "ZOuC9AHfya3PNiY9EiNrIAkfNtv2dSh6qg4KrTUXf1TSdGBAUp9z0/cA75a0ICIGj9tVZJPFTntSUSXpYldi3O/zy53Hnd1uPjXJ",
    "cX9I0iFJ5zTIGZeSEqYtkpalv+9wtdk5krZJ+mYhn7zA1Shfy48dD0CWk5KScr34rgvV/k7SC5JW+Ps7nET/fL3CtBYXksE1UZL0",
    "On+f2GCd5iku5bmv0CbS0WLgLh/a7eK86cn5z/h5liT1W6XjamVfT/JcSVdLut2cs0nSJz3Zk11DtcucV+oA4FxKnCzpAUuDqQ2u",
    "603qtp5OODGGWSFzsaRVJtw/TyTRt1wo+NpxswhLB5Gd3GB6H1lCIl/w9HQHHmZYPz5LVql/l2PQVwN3kiXJl7rKpKPu96Tu+2yy",
    "2qgzgK+R1Wf129/dlbTK3gH8EXBJRKxxUeJAJ2HFpNYtyHqrP2Tb4gc2wv6MLMV4K1nlx6Dj9TGcHuFuAzybLNAeXsrvCFl+90Wy",
    "LNGGiBjwby4BPkmWqVoP/EVEfG+4Xe/Js0wmK4xbYoKr2aodAB6PiNslzbU79gywJCJ2J41ev9Ik3gyEQhN9r/37K01oNX9eaEL7",
    "fER8rrAKYamw7MSxsW6nRfTZkn7NBWuPu275ORtFfcPRg0P9k4xE702zYXWWpDMT3fk2SetdLLfECYJh2yENzk2QdIvvt0/SX9sQ",
    "Kx8rIrqPrN/pUrKc7DT/PdUhPTkYv5KsPfTepGtuRBcLS7ii4UKmiVidBfy9Ay5ryfK7TyVifZvLcg90cP+jHJnk3KcCf2AJM9cS",
    "bF2yFPNeB352kaVZdzXKSEWXOXWC/dpZfsh8MfF8pdkXgJeSdabyVfWq3V4dNn2GZOJfT7bYzFvI0pcTvA9afN7m9aA7ViOF5TLK",
    "/LI4YL6jcNN9z3z1+M95ofG6DPD/G/ltlgjZRrQAAAAASUVORK5CYII=",
].joined()

private func glyphImage(winged: Bool) -> UIImage? {
    let b64 = winged ? queenGlyphBase64 : workerGlyphBase64
    guard let data = Data(base64Encoded: b64), let image = UIImage(data: data) else {
        return nil
    }
    return image.withRenderingMode(.alwaysTemplate)
}

// MARK: - View

struct NuptialWidgetEntryView: View {
    @Environment(\.widgetFamily) private var family
    var entry: FlightEntry

    private var band: Band? { bands[entry.bandKey] }

    private var label: String {
        if !entry.label.isEmpty { return entry.label }
        return band?.fallbackLabel ?? "..."
    }

    private var foreground: Color {
        guard let band = band else { return dynamic(textPrimary.0, textPrimary.1) }
        return dynamic(band.fgLight, band.fgDark)
    }

    private var background: Color {
        guard let band = band else { return dynamic(neutralBg.0, neutralBg.1) }
        return dynamic(band.bgLight, band.bgDark)
    }

    private var secondary: Color { dynamic(textSecondary.0, textSecondary.1) }

    /// Long localized band words (e.g. "Vielversprechend") need a smaller
    /// size to stay on one line, as on Android.
    private func labelSize(_ base: CGFloat) -> CGFloat {
        if label.count > 12 { return base * 0.68 }
        if label.count > 9 { return base * 0.82 }
        return base
    }

    private func glyph(width: CGFloat, color: Color) -> some View {
        Group {
            if let image = glyphImage(winged: band?.winged == true) {
                Image(uiImage: image)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .frame(width: width)
                    .foregroundColor(color)
            }
        }
        .accessibilityHidden(true)
    }

    // Compact: mirrors the 1-cell Android layout (glyph + band word + odds).
    private var smallBody: some View {
        VStack(spacing: 3) {
            glyph(width: 42, color: secondary)
            Text(label)
                .font(.system(size: labelSize(22), weight: .semibold))
                .minimumScaleFactor(0.7)
                .lineLimit(1)
                .foregroundColor(foreground)
            if !entry.odds.isEmpty {
                Text(entry.odds)
                    .font(.system(size: 12))
                    .lineLimit(1)
                    .foregroundColor(secondary)
            }
        }
        .padding(6)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // Wide: mirrors the fuller Android layout, heading included.
    private var mediumBody: some View {
        HStack(spacing: 14) {
            glyph(width: 74, color: secondary)
            VStack(alignment: .leading, spacing: 2) {
                Text("ANT FLIGHTS")
                    .font(.system(size: 11))
                    .kerning(1.2)
                    .foregroundColor(secondary)
                Text(label)
                    .font(.system(size: labelSize(30), weight: .semibold))
                    .minimumScaleFactor(0.6)
                    .lineLimit(1)
                    .foregroundColor(foreground)
                if !entry.odds.isEmpty {
                    Text(entry.odds)
                        .font(.system(size: 14))
                        .lineLimit(1)
                        .foregroundColor(secondary)
                }
            }
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // Lock Screen. These are rendered as a system tint, so no band colour.
    @available(iOSApplicationExtension 16.0, *)
    private var circularBody: some View {
        ZStack {
            AccessoryWidgetBackground()
            VStack(spacing: 0) {
                glyph(width: 26, color: .primary)
                if !entry.odds.isEmpty {
                    Text(entry.odds)
                        .font(.system(size: 10, weight: .semibold))
                        .minimumScaleFactor(0.6)
                        .lineLimit(1)
                }
            }
            .padding(4)
        }
    }

    @available(iOSApplicationExtension 16.0, *)
    private var rectangularBody: some View {
        HStack(spacing: 7) {
            glyph(width: 30, color: .primary)
            VStack(alignment: .leading, spacing: 1) {
                Text(label)
                    .font(.system(size: 15, weight: .semibold))
                    .lineLimit(1)
                    .minimumScaleFactor(0.7)
                if !entry.odds.isEmpty {
                    Text(entry.odds)
                        .font(.system(size: 12))
                        .lineLimit(1)
                }
            }
            Spacer(minLength: 0)
        }
    }

    private var inlineText: String {
        entry.odds.isEmpty ? label : label + " - " + entry.odds
    }

    @ViewBuilder
    private var content: some View {
        if #available(iOSApplicationExtension 16.0, *), family == .accessoryCircular {
            circularBody.widgetBackgroundCompat(Color.clear)
        } else if #available(iOSApplicationExtension 16.0, *), family == .accessoryRectangular {
            rectangularBody.widgetBackgroundCompat(Color.clear)
        } else if #available(iOSApplicationExtension 16.0, *), family == .accessoryInline {
            Text(inlineText).widgetBackgroundCompat(Color.clear)
        } else if family == .systemMedium {
            mediumBody.widgetBackgroundCompat(background)
        } else {
            smallBody.widgetBackgroundCompat(background)
        }
    }

    var body: some View {
        content.accessibilityLabel(accessibilityText)
    }

    private var accessibilityText: String {
        let base = "Ant flight outlook: \(label)."
        let queens = band?.winged == true ? " Winged queens are likely." : ""
        return base + queens + " Opens the app."
    }
}

private extension View {
    // iOS 17 requires containerBackground for widgets; earlier versions take a
    // plain background. This keeps one view working from iOS 14 through 17+.
    @ViewBuilder
    func widgetBackgroundCompat(_ color: Color) -> some View {
        if #available(iOSApplicationExtension 17.0, *) {
            containerBackground(for: .widget) { color }
        } else {
            background(color)
        }
    }
}

// MARK: - Widget

struct NuptialWidget: Widget {
    // The kind string must match the iOSName the Flutter side passes to
    // HomeWidget.updateWidget (lib/controller/widgets_mobile.dart).
    let kind: String = "NuptialWidget"

    private var families: [WidgetFamily] {
        if #available(iOSApplicationExtension 16.0, *) {
            return [.systemSmall, .systemMedium,
                    .accessoryCircular, .accessoryRectangular, .accessoryInline]
        }
        return [.systemSmall, .systemMedium]
    }

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: FlightProvider()) { entry in
            NuptialWidgetEntryView(entry: entry)
        }
        .configurationDisplayName("Nuptial Flight")
        .description("Shows today's Ant Flight Index at your location.")
        .supportedFamilies(families)
    }
}

@main
struct NuptialWidgetBundle: WidgetBundle {
    var body: some Widget {
        NuptialWidget()
    }
}
