# -*- coding: utf-8 -*-
"""Write ios/NuptialWidget/NuptialWidget.swift, glyphs embedded as base64.

The extension's only source file is already a member of the Xcode target, so
embedding the two ant glyphs as base64 literals keeps everything in that one
file. Adding an asset catalogue instead would mean editing project.pbxproj,
which was built on a Mac with the xcodeproj gem and is not something to hand-
edit blind from here.
"""
import base64
import io
import os
import textwrap
from PIL import Image

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
GLYPH_SRC = os.path.join(REPO, 'android/app/src/main/res/drawable-xxxhdpi')
OUT = os.path.join(REPO, 'ios/NuptialWidget/NuptialWidget.swift')


def glyph_b64(name, width=120):
    im = Image.open(os.path.join(GLYPH_SRC, 'widget_ant_%s.png' % name)).convert('RGBA')
    h = max(1, round(width * im.size[1] / im.size[0]))
    im = im.resize((width, h), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, 'PNG', optimize=True)
    return base64.b64encode(buf.getvalue()).decode('ascii')


def wrap(b64, indent='    '):
    """Emit an array of chunks joined at runtime.

    Chaining ~54 string literals with `+` is exactly the shape that trips
    Swift's "unable to type-check this expression in reasonable time", so
    build an array literal and .joined() it instead.
    """
    chunks = textwrap.wrap(b64, 100)
    nl = chr(10)
    body = (nl + indent).join('"%s",' % c for c in chunks)
    return '[' + nl + indent + body + nl + '].joined()'


SWIFT = '''//
//  NuptialWidget.swift
//  NuptialWidget
//
//  iOS home-screen widget for the Ant Nuptial Flight Predictor - the
//  counterpart of the Android AppWidgetProvider, and kept deliberately in
//  step with it: the same five Ant Flight Index bands, the same palette
//  (res/values/colors.xml + values-night), the same calibrated odds line and
//  the same ant glyph, which is a wingless worker on quiet days and a winged
//  queen once a flight is likely. Change one side, change the other.
//
//  Sizes. Android lets you resize one widget between a 1-cell glyph+word and
//  a wider cell with the odds as well. iOS cannot do that: a placed widget
//  has a fixed family, and there is no 1x1 home-screen family at all -
//  .systemSmall already occupies a 2x2 block of icons and is the floor Apple
//  offers. So the nearest equivalent is to publish several families and let
//  you pick when adding: .systemSmall mirrors the compact Android layout,
//  .systemMedium mirrors the wider one, and the Lock Screen accessories
//  (iOS 16+) are the genuinely small option.
//
//  Generated by scripts/icon/gen_ios_widget.py - the two glyphs are the same
//  Myrmecia artwork as the app icon, embedded as base64 because this file is
//  the extension's only target member.
//

import WidgetKit
import SwiftUI

private let appGroupId = "group.au.com.bitbot.nuptialflight"

// MARK: - Bands

private struct Band {
    let bgLight: UInt32
    let bgDark: UInt32
    let fgLight: UInt32
    let fgDark: UInt32
    let fallbackLabel: String
    /// Winged queen once a flight is plausible; wingless worker below.
    let winged: Bool
}

private let bands: [String: Band] = [
    "noFly": Band(bgLight: 0xECEDEA, bgDark: 0x262B27,
                  fgLight: 0x55615A, fgDark: 0x9AA69C,
                  fallbackLabel: "No-fly", winged: false),
    "quiet": Band(bgLight: 0xF6E2DF, bgDark: 0x3A2523,
                  fgLight: 0xA04A42, fgDark: 0xE09A92,
                  fallbackLabel: "Quiet", winged: false),
    "watchful": Band(bgLight: 0xF3E5C8, bgDark: 0x3A3120,
                     fgLight: 0x8A5B10, fgDark: 0xDCB573,
                     fallbackLabel: "Watchful", winged: false),
    "promising": Band(bgLight: 0xE9F0D8, bgDark: 0x2C331F,
                      fgLight: 0x5E7D2E, fgDark: 0xAFC97A,
                      fallbackLabel: "Promising", winged: true),
    "prime": Band(bgLight: 0xD7E8DC, bgDark: 0x22352A,
                  fgLight: 0x2E7D43, fgDark: 0x7FCE96,
                  fallbackLabel: "Prime", winged: true),
]

private let neutralBg: (UInt32, UInt32) = (0xE8EAED, 0x2A2C2F)
private let textPrimary: (UInt32, UInt32) = (0x1A1C1E, 0xF1F3F4)
private let textSecondary: (UInt32, UInt32) = (0x44474A, 0xC7CACD)

private func dynamic(_ light: UInt32, _ dark: UInt32) -> Color {
    Color(UIColor { trait in
        let v = trait.userInterfaceStyle == .dark ? dark : light
        return UIColor(red: CGFloat((v >> 16) & 0xFF) / 255.0,
                       green: CGFloat((v >> 8) & 0xFF) / 255.0,
                       blue: CGFloat(v & 0xFF) / 255.0,
                       alpha: 1.0)
    })
}

// MARK: - Timeline

struct FlightEntry: TimelineEntry {
    let date: Date
    let bandKey: String
    let label: String
    let odds: String
}

struct FlightProvider: TimelineProvider {
    func placeholder(in context: Context) -> FlightEntry {
        FlightEntry(date: Date(), bandKey: "prime", label: "Prime", odds: "1 in 7")
    }

    func getSnapshot(in context: Context, completion: @escaping (FlightEntry) -> Void) {
        completion(loadEntry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<FlightEntry>) -> Void) {
        // The Flutter app reloads this timeline whenever it saves a new
        // outlook, so the hourly refresh is only a fallback for stale data.
        let next = Calendar.current.date(byAdding: .hour, value: 1, to: Date())
            ?? Date().addingTimeInterval(3600)
        completion(Timeline(entries: [loadEntry()], policy: .after(next)))
    }

    private func loadEntry() -> FlightEntry {
        let store = UserDefaults(suiteName: appGroupId)
        let percentage = store?.integer(forKey: "_percentage") ?? 0
        var key = store?.string(forKey: "_band") ?? ""

        // Band key written by 2.20+; fall back to the old percentage
        // thresholds right after an upgrade so the widget is never blank.
        // Mirrors the same fallback in AppWidgetProvider.kt.
        if key.isEmpty {
            if percentage <= 0 {
                key = ""
            } else if percentage < 50 {
                key = "quiet"
            } else if percentage < 60 {
                key = "watchful"
            } else {
                key = "prime"
            }
        }

        return FlightEntry(date: Date(),
                           bandKey: key,
                           label: store?.string(forKey: "_band_label") ?? "",
                           odds: store?.string(forKey: "_odds") ?? "")
    }
}

// MARK: - Ant glyphs

private let workerGlyphBase64 = %WORKER%

private let queenGlyphBase64 = %QUEEN%

private func glyphImage(winged: Bool) -> UIImage? {
    let b64 = winged ? queenGlyphBase64 : workerGlyphBase64
    guard let data = Data(base64Encoded: b64), let image = UIImage(data: data) else {
        return nil
    }
    return image.withRenderingMode(.alwaysTemplate)
}

// MARK: - View

struct NuptialWidgetEntryView: View {
    @Environment(\\.widgetFamily) private var family
    var entry: FlightEntry

    private var band: Band? { bands[entry.bandKey] }

    private var label: String {
        if !entry.label.isEmpty { return entry.label }
        return band?.fallbackLabel ?? "..."
    }

    private var foreground: Color {
        guard let band = band else { return dynamic(textPrimary.0, textPrimary.1) }
        return dynamic(band.fgLight, band.fgDark)
    }

    private var background: Color {
        guard let band = band else { return dynamic(neutralBg.0, neutralBg.1) }
        return dynamic(band.bgLight, band.bgDark)
    }

    private var secondary: Color { dynamic(textSecondary.0, textSecondary.1) }

    /// Long localized band words (e.g. "Vielversprechend") need a smaller
    /// size to stay on one line, as on Android.
    private func labelSize(_ base: CGFloat) -> CGFloat {
        if label.count > 12 { return base * 0.68 }
        if label.count > 9 { return base * 0.82 }
        return base
    }

    private func glyph(width: CGFloat, color: Color) -> some View {
        Group {
            if let image = glyphImage(winged: band?.winged == true) {
                Image(uiImage: image)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .frame(width: width)
                    .foregroundColor(color)
            }
        }
        .accessibilityHidden(true)
    }

    // Compact: mirrors the 1-cell Android layout (glyph + band word + odds).
    private var smallBody: some View {
        VStack(spacing: 3) {
            glyph(width: 42, color: secondary)
            Text(label)
                .font(.system(size: labelSize(22), weight: .semibold))
                .minimumScaleFactor(0.7)
                .lineLimit(1)
                .foregroundColor(foreground)
            if !entry.odds.isEmpty {
                Text(entry.odds)
                    .font(.system(size: 12))
                    .lineLimit(1)
                    .foregroundColor(secondary)
            }
        }
        .padding(6)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // Wide: mirrors the fuller Android layout, heading included.
    private var mediumBody: some View {
        HStack(spacing: 14) {
            glyph(width: 74, color: secondary)
            VStack(alignment: .leading, spacing: 2) {
                Text("ANT FLIGHTS")
                    .font(.system(size: 11))
                    .kerning(1.2)
                    .foregroundColor(secondary)
                Text(label)
                    .font(.system(size: labelSize(30), weight: .semibold))
                    .minimumScaleFactor(0.6)
                    .lineLimit(1)
                    .foregroundColor(foreground)
                if !entry.odds.isEmpty {
                    Text(entry.odds)
                        .font(.system(size: 14))
                        .lineLimit(1)
                        .foregroundColor(secondary)
                }
            }
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 16)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // Lock Screen. These are rendered as a system tint, so no band colour.
    @available(iOSApplicationExtension 16.0, *)
    private var circularBody: some View {
        ZStack {
            AccessoryWidgetBackground()
            VStack(spacing: 0) {
                glyph(width: 26, color: .primary)
                if !entry.odds.isEmpty {
                    Text(entry.odds)
                        .font(.system(size: 10, weight: .semibold))
                        .minimumScaleFactor(0.6)
                        .lineLimit(1)
                }
            }
            .padding(4)
        }
    }

    @available(iOSApplicationExtension 16.0, *)
    private var rectangularBody: some View {
        HStack(spacing: 7) {
            glyph(width: 30, color: .primary)
            VStack(alignment: .leading, spacing: 1) {
                Text(label)
                    .font(.system(size: 15, weight: .semibold))
                    .lineLimit(1)
                    .minimumScaleFactor(0.7)
                if !entry.odds.isEmpty {
                    Text(entry.odds)
                        .font(.system(size: 12))
                        .lineLimit(1)
                }
            }
            Spacer(minLength: 0)
        }
    }

    private var inlineText: String {
        entry.odds.isEmpty ? label : label + " - " + entry.odds
    }

    @ViewBuilder
    private var content: some View {
        if #available(iOSApplicationExtension 16.0, *), family == .accessoryCircular {
            circularBody.widgetBackgroundCompat(Color.clear)
        } else if #available(iOSApplicationExtension 16.0, *), family == .accessoryRectangular {
            rectangularBody.widgetBackgroundCompat(Color.clear)
        } else if #available(iOSApplicationExtension 16.0, *), family == .accessoryInline {
            Text(inlineText).widgetBackgroundCompat(Color.clear)
        } else if family == .systemMedium {
            mediumBody.widgetBackgroundCompat(background)
        } else {
            smallBody.widgetBackgroundCompat(background)
        }
    }

    var body: some View {
        content.accessibilityLabel(accessibilityText)
    }

    private var accessibilityText: String {
        let base = "Ant flight outlook: \\(label)."
        let queens = band?.winged == true ? " Winged queens are likely." : ""
        return base + queens + " Opens the app."
    }
}

private extension View {
    // iOS 17 requires containerBackground for widgets; earlier versions take a
    // plain background. This keeps one view working from iOS 14 through 17+.
    @ViewBuilder
    func widgetBackgroundCompat(_ color: Color) -> some View {
        if #available(iOSApplicationExtension 17.0, *) {
            containerBackground(for: .widget) { color }
        } else {
            background(color)
        }
    }
}

// MARK: - Widget

struct NuptialWidget: Widget {
    // The kind string must match the iOSName the Flutter side passes to
    // HomeWidget.updateWidget (lib/controller/widgets_mobile.dart).
    let kind: String = "NuptialWidget"

    private var families: [WidgetFamily] {
        if #available(iOSApplicationExtension 16.0, *) {
            return [.systemSmall, .systemMedium,
                    .accessoryCircular, .accessoryRectangular, .accessoryInline]
        }
        return [.systemSmall, .systemMedium]
    }

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: FlightProvider()) { entry in
            NuptialWidgetEntryView(entry: entry)
        }
        .configurationDisplayName("Nuptial Flight")
        .description("Shows today's Ant Flight Index at your location.")
        .supportedFamilies(families)
    }
}

@main
struct NuptialWidgetBundle: WidgetBundle {
    var body: some Widget {
        NuptialWidget()
    }
}
'''

if __name__ == '__main__':
    swift = SWIFT.replace('%WORKER%', wrap(glyph_b64('worker')))
    swift = swift.replace('%QUEEN%', wrap(glyph_b64('queen')))
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(swift)
    print('wrote %s (%d bytes)' % (OUT, len(swift)))
