# -*- coding: utf-8 -*-
"""Write ios/NuptialWidget/NuptialWidget.swift, glyphs embedded as base64.

The extension's only source file is already a member of the Xcode target, so
embedding the two ant glyphs as base64 literals keeps everything in that one
file. Adding an asset catalogue instead would mean editing project.pbxproj,
which was built on a Mac with the xcodeproj gem and is not something to hand-
edit blind from here.
"""
import base64
import io
import os
import textwrap
from PIL import Image

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
GLYPH_SRC = os.path.join(REPO, 'android/app/src/main/res/drawable-xxxhdpi')
OUT = os.path.join(REPO, 'ios/NuptialWidget/NuptialWidget.swift')


def glyph_b64(name, width=120):
    im = Image.open(os.path.join(GLYPH_SRC, 'widget_ant_%s.png' % name)).convert('RGBA')
    h = max(1, round(width * im.size[1] / im.size[0]))
    im = im.resize((width, h), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, 'PNG', optimize=True)
    return base64.b64encode(buf.getvalue()).decode('ascii')


def wrap(b64, indent='    '):
    """Emit an array of chunks joined at runtime.

    Chaining ~54 string literals with `+` is exactly the shape that trips
    Swift's "unable to type-check this expression in reasonable time", so
    build an array literal and .joined() it instead.
    """
    chunks = textwrap.wrap(b64, 100)
    nl = chr(10)
    body = (nl + indent).join('"%s",' % c for c in chunks)
    return '[' + nl + indent + body + nl + '].joined()'


SWIFT = '''//
//  NuptialWidget.swift
//  NuptialWidget
//
//  iOS home-screen widget for the Ant Nuptial Flight Predictor - the
//  counterpart of the Android AppWidgetProvider, and kept deliberately in
//  step with it: the same five Ant Flight Index bands, the same palette
//  (res/values/colors.xml + values-night), the same calibrated odds line and
//  the same ant glyph, which is a wingless worker on quiet days and a winged
//  queen once a flight is likely. Change one side, change the other.
//
//  Generated by scripts/icon/gen_ios_widget.py - the two glyphs are the same
//  Myrmecia artwork as the app icon, embedded as base64 because this file is
//  the extension's only target member.
//

import WidgetKit
import SwiftUI

private let appGroupId = "group.au.com.bitbot.nuptialflight"

// MARK: - Bands

private struct Band {
    let bgLight: UInt32
    let bgDark: UInt32
    let fgLight: UInt32
    let fgDark: UInt32
    let fallbackLabel: String
    /// Winged queen once a flight is plausible; wingless worker below.
    let winged: Bool
}

private let bands: [String: Band] = [
    "noFly": Band(bgLight: 0xECEDEA, bgDark: 0x262B27,
                  fgLight: 0x55615A, fgDark: 0x9AA69C,
                  fallbackLabel: "No-fly", winged: false),
    "quiet": Band(bgLight: 0xF6E2DF, bgDark: 0x3A2523,
                  fgLight: 0xA04A42, fgDark: 0xE09A92,
                  fallbackLabel: "Quiet", winged: false),
    "watchful": Band(bgLight: 0xF3E5C8, bgDark: 0x3A3120,
                     fgLight: 0x8A5B10, fgDark: 0xDCB573,
                     fallbackLabel: "Watchful", winged: false),
    "promising": Band(bgLight: 0xE9F0D8, bgDark: 0x2C331F,
                      fgLight: 0x5E7D2E, fgDark: 0xAFC97A,
                      fallbackLabel: "Promising", winged: true),
    "prime": Band(bgLight: 0xD7E8DC, bgDark: 0x22352A,
                  fgLight: 0x2E7D43, fgDark: 0x7FCE96,
                  fallbackLabel: "Prime", winged: true),
]

private let neutralBg: (UInt32, UInt32) = (0xE8EAED, 0x2A2C2F)
private let textPrimary: (UInt32, UInt32) = (0x1A1C1E, 0xF1F3F4)
private let textSecondary: (UInt32, UInt32) = (0x44474A, 0xC7CACD)

private func dynamic(_ light: UInt32, _ dark: UInt32) -> Color {
    Color(UIColor { trait in
        let v = trait.userInterfaceStyle == .dark ? dark : light
        return UIColor(red: CGFloat((v >> 16) & 0xFF) / 255.0,
                       green: CGFloat((v >> 8) & 0xFF) / 255.0,
                       blue: CGFloat(v & 0xFF) / 255.0,
                       alpha: 1.0)
    })
}

// MARK: - Timeline

struct FlightEntry: TimelineEntry {
    let date: Date
    let bandKey: String
    let label: String
    let odds: String
}

struct FlightProvider: TimelineProvider {
    func placeholder(in context: Context) -> FlightEntry {
        FlightEntry(date: Date(), bandKey: "prime", label: "Prime", odds: "1 in 7")
    }

    func getSnapshot(in context: Context, completion: @escaping (FlightEntry) -> Void) {
        completion(loadEntry())
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<FlightEntry>) -> Void) {
        // The Flutter app reloads this timeline whenever it saves a new
        // outlook, so the hourly refresh is only a fallback for stale data.
        let next = Calendar.current.date(byAdding: .hour, value: 1, to: Date())
            ?? Date().addingTimeInterval(3600)
        completion(Timeline(entries: [loadEntry()], policy: .after(next)))
    }

    private func loadEntry() -> FlightEntry {
        let store = UserDefaults(suiteName: appGroupId)
        let percentage = store?.integer(forKey: "_percentage") ?? 0
        var key = store?.string(forKey: "_band") ?? ""

        // Band key written by 2.20+; fall back to the old percentage
        // thresholds right after an upgrade so the widget is never blank.
        // Mirrors the same fallback in AppWidgetProvider.kt.
        if key.isEmpty {
            if percentage <= 0 {
                key = ""
            } else if percentage < 50 {
                key = "quiet"
            } else if percentage < 60 {
                key = "watchful"
            } else {
                key = "prime"
            }
        }

        return FlightEntry(date: Date(),
                           bandKey: key,
                           label: store?.string(forKey: "_band_label") ?? "",
                           odds: store?.string(forKey: "_odds") ?? "")
    }
}

// MARK: - Ant glyphs

private let workerGlyphBase64 = %WORKER%

private let queenGlyphBase64 = %QUEEN%

private func glyphImage(winged: Bool) -> UIImage? {
    let b64 = winged ? queenGlyphBase64 : workerGlyphBase64
    guard let data = Data(base64Encoded: b64), let image = UIImage(data: data) else {
        return nil
    }
    return image.withRenderingMode(.alwaysTemplate)
}

// MARK: - View

struct NuptialWidgetEntryView: View {
    var entry: FlightEntry

    private var band: Band? { bands[entry.bandKey] }

    private var label: String {
        if !entry.label.isEmpty { return entry.label }
        return band?.fallbackLabel ?? "..."
    }

    private var foreground: Color {
        guard let band = band else { return dynamic(textPrimary.0, textPrimary.1) }
        return dynamic(band.fgLight, band.fgDark)
    }

    private var background: Color {
        guard let band = band else { return dynamic(neutralBg.0, neutralBg.1) }
        return dynamic(band.bgLight, band.bgDark)
    }

    /// Long localized band words (e.g. "Vielversprechend") need a smaller
    /// size to stay on one line, as on Android.
    private var labelSize: CGFloat {
        if label.count > 12 { return 15 }
        if label.count > 9 { return 18 }
        return 22
    }

    var body: some View {
        VStack(spacing: 3) {
            if let image = glyphImage(winged: band?.winged == true) {
                Image(uiImage: image)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .frame(width: 42)
                    .foregroundColor(dynamic(textSecondary.0, textSecondary.1))
                    .accessibilityHidden(true)
            }

            Text(label)
                .font(.system(size: labelSize, weight: .semibold))
                .minimumScaleFactor(0.7)
                .lineLimit(1)
                .foregroundColor(foreground)

            if !entry.odds.isEmpty {
                Text(entry.odds)
                    .font(.system(size: 12))
                    .lineLimit(1)
                    .foregroundColor(dynamic(textSecondary.0, textSecondary.1))
            }
        }
        .padding(6)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .widgetBackgroundCompat(background)
        .accessibilityLabel(accessibilityText)
    }

    private var accessibilityText: String {
        let base = "Ant flight outlook: \\(label)."
        let queens = band?.winged == true ? " Winged queens are likely." : ""
        return base + queens + " Opens the app."
    }
}

private extension View {
    // iOS 17 requires containerBackground for widgets; earlier versions take a
    // plain background. This keeps one view working from iOS 14 through 17+.
    @ViewBuilder
    func widgetBackgroundCompat(_ color: Color) -> some View {
        if #available(iOSApplicationExtension 17.0, *) {
            containerBackground(for: .widget) { color }
        } else {
            background(color)
        }
    }
}

// MARK: - Widget

struct NuptialWidget: Widget {
    // The kind string must match the iOSName the Flutter side passes to
    // HomeWidget.updateWidget (lib/controller/widgets_mobile.dart).
    let kind: String = "NuptialWidget"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: FlightProvider()) { entry in
            NuptialWidgetEntryView(entry: entry)
        }
        .configurationDisplayName("Nuptial Flight")
        .description("Shows today's Ant Flight Index at your location.")
        .supportedFamilies([.systemSmall])
    }
}

@main
struct NuptialWidgetBundle: WidgetBundle {
    var body: some Widget {
        NuptialWidget()
    }
}
'''

if __name__ == '__main__':
    swift = SWIFT.replace('%WORKER%', wrap(glyph_b64('worker')))
    swift = swift.replace('%QUEEN%', wrap(glyph_b64('queen')))
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(swift)
    print('wrote %s (%d bytes)' % (OUT, len(swift)))
